export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const CREATE_BUCKETLIST_SUCCESS = 'CREATE_BUCKETLIST_SUCCESS';
export const DISPLAY_BUCKETLIST_SUCCESS = 'DISPLAY_BUCKETLIST_SUCCESS';
export const UPDATE_BUCKETLIST_SUCCESS = 'UPDATE_BUCKETLIST_SUCCESS';
export const DELETE_BUCKETLIST_SUCCESS = 'DELETE_BUCKETLIST_SUCCESS';

export const CREATE_BUCKETLISTITMES_SUCCESS = 'CREATE_BUCKETLISTITMES_SUCCESS';
export const UPDATE_BUCKETLISTITMES_SUCCESS = 'UPDATE_BUCKETLISTITMES_SUCCESS';
export const DISPLAY_BUCKETLISTITEM_SUCCESS = 'DISPLAY_BUCKETLISTITEM_SUCCESS';
